name: datascience
dependencies:
- cycler
- decorator
- fontconfig
- freetype
- ipython
- ipython_genutils
- libgfortran
- libpng
- libxml2
- matplotlib
- mkl
- numpy
- openssl
- pandas
- path.py
- pexpect
- pickleshare
- pip
- pyparsing
- pyqt
- python
- python-dateutil
- pytz
- qt
- readline
- scipy
- setuptools
- simplegeneric
- sip
- six
- sqlite
- tk
- traitlets
- wheel
- xz
- zlib
- pip:
  - alabaster
  - babel
  - docutils
  - folium==0.2.1
  - ipython-genutils
  - jinja2
  - markupsafe
  - pygments
  - snowballstemmer
  - sphinx
  - sphinx-rtd-theme

