name: datascience
dependencies:
- coveralls
- cycler
- decorator
- fontconfig
- freetype
- ipython
- ipython_genutils
- libpng
- libxml2
- matplotlib
- mkl
- numpy
- openssl
- pandas
- path.py
- pexpect
- pickleshare
- pip
- pyparsing
- pyqt
- pytest
- pytest-cov
- python
- python-dateutil
- pytz
- qt
- readline
- scipy
- setuptools
- simplegeneric
- sip
- six
- sqlite
- tk
- traitlets
- wheel
- xz
- zlib
- pip:
  - alabaster
  - babel
  - branca
  - docutils
  - folium==0.11.0
  - ipython-genutils
  - jinja2
  - jupyter
  - jupyter_client
  - markupsafe
  - nbconvert
  - nbformat
  - nbsphinx
  - nbval
  - plotly
  - pygments
  - snowballstemmer
  - sphinx
  - sphinx-rtd-theme
